Repository NicholasBottone/Wordify, pull requests merged in 2022-05, with the labels that each got.

#1 Create data types and backend models
  lib/middlewares/auth.ts
  lib/mongoose.ts
  models/ChallengePuzzle.ts
  models/DailyPuzzle.ts
  models/User.ts
  package-lock.json
  package.json
  pages/api/hello.ts
  types/IChallengePuzzle.ts
  types/IDailyPuzzle.ts
  types/IPuzzle.ts
  types/IUser.ts
Labels: enhancement

#7 Add Passport Google Authentication to API
  lib/auth/passport.ts
  lib/auth/session.ts
  lib/endpoints/express.ts
  lib/hooks/auth.ts
  lib/middlewares/auth.ts
  lib/middlewares/mongoose.ts
  lib/middlewares/user.ts
  package-lock.json
  package.json
  pages/api/auth/callback.ts
  pages/api/auth/index.ts
  pages/api/auth/login.ts
  pages/api/auth/logout.ts
  pages/api/hello.ts
Labels: enhancement

#8 Add user to the header using useUser hook
  components/Header.tsx
  lib/auth/passport.ts
  lib/hooks/auth.ts
Labels: enhancement

#10 Add badges to README and remove unused NPM packages
  README.md
  package-lock.json
  package.json
Labels: documentation

#6 Gamescreen
  components/Board.tsx
  components/GameOver.tsx
  components/Key.tsx
  components/Keyboard.tsx
  components/Letter.tsx
  components/words.ts
  pages/game.tsx
  styles/globals.css
Labels: enhancement

#9 Daily puzzle API and cron job
  .github/workflows/nightly-cron.yml
  lib/auth/passport.ts
  lib/hooks/puzzle.ts
  models/ChallengePuzzle.ts
  models/DailyPuzzle.ts
  pages/api/cron/midnight.ts
  pages/api/puzzle/daily/[daysAgo].ts
  pages/api/puzzle/daily/create.ts
  pages/api/puzzle/daily/index.ts
Labels: enhancement

#11 Fix nightly cron in GitHub Actions
  .github/workflows/nightly-cron.yml
Labels: bug

#14 Backend getting other user profiles and friend lists
  lib/hooks/profile.ts
  pages/api/hello.ts
  pages/api/user/[id].ts
  pages/api/user/friend.ts
Labels: enhancement

#13 feat: connected with backend to get daily puzzle
  components/GameOver.tsx
  components/Key.tsx
  components/Letter.tsx
  lib/hooks/puzzle.ts
  lib/words/wordVerifier.ts
  lib/words/words.ts
  pages/api/puzzle/daily/index.ts
  pages/game.tsx
Labels: enhancement

#16 Query users api
  lib/hooks/profile.ts
  pages/api/user/search.ts
Labels: enhancement

#17 fix: send correct board data to backend
  components/Letter.tsx
  pages/game.tsx
Labels: bug

#15 integrated backend to stat screen
  components/Board.tsx
  components/ProfileBoardBlock.tsx
  components/ProfileBoardRow.tsx
  package-lock.json
  pages/index.tsx
  pages/profile.tsx
  pages/statistics.tsx
  styles/globals.css
Labels: enhancement

#19 feat: added logo and title to home page, added styling to buttons
  pages/index.tsx
  public/icon.png
  public/wordify-logo.png
  styles/globals.css
Labels: enhancement

#23 Freeplay
  components/GameOver.tsx
  lib/hooks/auth.ts
  pages/game.tsx
Labels: enhancement

#25 Daily info
  pages/daily-info.tsx
  styles/globals.css
Labels: enhancement

#27 Menubar
  components/Header.tsx
  pages/about.tsx
  pages/daily-info.tsx
  pages/privacy.tsx
  public/blueno.png
Labels: enhancement

#28 Timer sent to backend
  components/Timer.tsx
  pages/game.tsx
Labels: enhancement

#29 Add about page to navbar
  components/Header.tsx
  pages/about.tsx
Labels: enhancement

#32 feat: added CSS styling to home page background
  components/Head.tsx
  components/Header.tsx
  pages/about.tsx
  pages/daily-info.tsx
  pages/game.tsx
  pages/index.tsx
  pages/privacy.tsx
  public/favicon.ico
  public/vercel.svg
  styles/globals.css
Labels: enhancement

#33 Add friends screen, search for other profiles screen, also fix navbar bug and gamescreen bug
  components/Header.tsx
  components/Layout.tsx
  lib/auth/passport.ts
  lib/hooks/profile.ts
  package-lock.json
  package.json
  pages/about.tsx
  pages/api/puzzle/daily/index.ts
  pages/api/user/friend.ts
  pages/daily-info.tsx
  pages/friends.tsx
  pages/game.tsx
  pages/index.tsx
  pages/privacy.tsx
  pages/profile.tsx
  pages/statistics.tsx
  styles/globals.css
  types/IPuzzle.ts
  types/IUser.ts
Labels: bug, enhancement

#34 Profile responsiveness
  components/Board.tsx
  components/GameOver.tsx
  lib/hooks/profile.ts
  pages/daily-info.tsx
  pages/friends.tsx
  pages/game.tsx
  pages/profile.tsx
  pages/statistics.tsx
  styles/globals.css
Labels: bug, enhancement

#35 More e2e testing and documentation
  README.md
  Specifications.md
  playwright.config.ts
  tests/2fa.ts
  tests/api/apiSecurity.spec.ts
  tests/e2e/friendsPage.spec.ts
  tests/e2e/navLinks.spec.ts
  tests/e2e/playAsGuest.spec.ts
  tests/e2e/profilePage.spec.ts
Labels: documentation, testing

#36 Text changes
  components/Header.tsx
  pages/about.tsx
  pages/daily-info.tsx
  pages/friends.tsx
  pages/instructions.tsx
Labels: documentation
